name: "Feature request"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: "### Motivation"
  - type: textarea
    attributes:
      id: motivation
      label: Why is this needed?
