# SPDX-License-Identifier: BUSL-1.1
[package]
name = "tool_hook_macro"
license = "BUSL-1.1"
license-file = "../../../LICENSE"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
