// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: sdk/go/axcp_local/telemetry.proto

package axcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryDatagram represents a single telemetry data point
type TelemetryDatagram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                      // Unique identifier for tracing
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`                                                                       // Name of the metric (e.g., "cpu.usage", "memory.used")
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`                                                                       // Numeric value of the metric
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                // Unix timestamp in nanoseconds
	Profile       int32                  `protobuf:"varint,5,opt,name=profile,proto3" json:"profile,omitempty"`                                                                    // Privacy profile level (1-5)
	Tags          map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional key-value pairs for context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryDatagram) Reset() {
	*x = TelemetryDatagram{}
	mi := &file_sdk_go_axcp_local_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryDatagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryDatagram) ProtoMessage() {}

func (x *TelemetryDatagram) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_axcp_local_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryDatagram.ProtoReflect.Descriptor instead.
func (*TelemetryDatagram) Descriptor() ([]byte, []int) {
	return file_sdk_go_axcp_local_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryDatagram) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TelemetryDatagram) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TelemetryDatagram) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryDatagram) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryDatagram) GetProfile() int32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *TelemetryDatagram) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_sdk_go_axcp_local_telemetry_proto protoreflect.FileDescriptor

const file_sdk_go_axcp_local_telemetry_proto_rawDesc = "" +
	"\n" +
	"!sdk/go/axcp_local/telemetry.proto\x12\x04axcp\"\x84\x02\n" +
	"\x11TelemetryDatagram\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\x05R\aprofile\x125\n" +
	"\x04tags\x18\x06 \x03(\v2!.axcp.TelemetryDatagram.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/tradephantom/axcp-spec/sdk/go/axcpb\x06proto3"

var (
	file_sdk_go_axcp_local_telemetry_proto_rawDescOnce sync.Once
	file_sdk_go_axcp_local_telemetry_proto_rawDescData []byte
)

func file_sdk_go_axcp_local_telemetry_proto_rawDescGZIP() []byte {
	file_sdk_go_axcp_local_telemetry_proto_rawDescOnce.Do(func() {
		file_sdk_go_axcp_local_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_go_axcp_local_telemetry_proto_rawDesc), len(file_sdk_go_axcp_local_telemetry_proto_rawDesc)))
	})
	return file_sdk_go_axcp_local_telemetry_proto_rawDescData
}

var file_sdk_go_axcp_local_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_go_axcp_local_telemetry_proto_goTypes = []any{
	(*TelemetryDatagram)(nil), // 0: axcp.TelemetryDatagram
	nil,                       // 1: axcp.TelemetryDatagram.TagsEntry
}
var file_sdk_go_axcp_local_telemetry_proto_depIdxs = []int32{
	1, // 0: axcp.TelemetryDatagram.tags:type_name -> axcp.TelemetryDatagram.TagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_go_axcp_local_telemetry_proto_init() }
func file_sdk_go_axcp_local_telemetry_proto_init() {
	if File_sdk_go_axcp_local_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_go_axcp_local_telemetry_proto_rawDesc), len(file_sdk_go_axcp_local_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_go_axcp_local_telemetry_proto_goTypes,
		DependencyIndexes: file_sdk_go_axcp_local_telemetry_proto_depIdxs,
		MessageInfos:      file_sdk_go_axcp_local_telemetry_proto_msgTypes,
	}.Build()
	File_sdk_go_axcp_local_telemetry_proto = out.File
	file_sdk_go_axcp_local_telemetry_proto_goTypes = nil
	file_sdk_go_axcp_local_telemetry_proto_depIdxs = nil
}
