# PII schema for Enterprise Secure Telemetry
# Any JSON/protobuf field path listed here will be redacted before
# signing and persisting telemetry datagrams.
# Paths are specified using dot notation.
fields:
  - user.email
  - user.phone
  - device.serial_number
  - location.lat
  - location.lon
