export { Agent, type AgentOptions } from "./agent.js";
export {
  DID_AUTH_TRANSCRIPT_VERSION,
  DEFAULT_PROFILE_SECURE_BASELINE,
  DEFAULT_PROTOCOL_VERSION,
  buildAuthTranscript,
  decodeEnvelope,
  encodeEnvelope,
  newEnvelope,
  signEnvelope,
  signingPayload,
  verifyEnvelope,
  type NewEnvelopeOptions,
  type SignEnvelopeOptions,
  type VerifyEnvelopeOptions,
} from "./envelope.js";
export {
  AXCPError,
  DIDError,
  DIDResolutionError,
  DeprecatedProfileError,
  InvalidCapabilitiesError,
  InvalidDIDFormat,
  InvalidEnvelopeError,
  InvalidPrivateKeyError,
  InvalidReplayConfigError,
  KeyMismatchError,
  NegotiationError,
  NoProfileOverlapError,
  NoSignatureAlgorithmOverlapError,
  ReplayDetectedError,
  ReplayError,
  SequenceTooOldError,
  SignatureError,
  SignatureMissingError,
  SignatureVerificationError,
  TimestampError,
  TimestampExpiredError,
  TimestampFutureError,
  TimestampMissingError,
  TransportClosedError,
  TransportConfigError,
  TransportError,
  TransportFrameError,
  TransportTimeoutError,
  TransportUnsupportedError,
} from "./errors.js";
export {
  DID,
  DID_KEY_ED25519_MULTICODEC_PREFIX,
  ED25519_PRIVATE_SEED_SIZE,
  ED25519_PUBLIC_KEY_SIZE,
  ED25519_SIGNATURE_SIZE,
  Identity,
  InMemoryDIDResolver,
  didKeyFromPublicKey,
  publicKeyFromDidKey,
  resolveEd25519PublicKey,
  verifySignature,
  type DIDDocument,
  type DIDResolver,
  type IdentityJson,
  type ParsedDID,
  type PublicKeyRecord,
} from "./identity.js";
export {
  DEFAULT_CAPABILITIES,
  DEFAULT_CLIENT_HELLO,
  PROTOCOL_VERSION_V1,
  Profile,
  SIG_ALGO_ED25519,
  negotiate,
  type Capabilities,
  type ClientHello,
  type NegotiateOptions,
  type ServerHello,
} from "./profile.js";
export { ReplayProtector, type ReplayProtectorOptions } from "./replay.js";
export {
  DEFAULT_CLOCK_SKEW_MS,
  DEFAULT_MAX_TIMESTAMP_AGE_MS,
  TimestampValidator,
  dateFromMs,
  nowMs,
  rfc3339SecondsFromMs,
  type TimestampValidatorOptions,
} from "./timestamp.js";
export {
  DEFAULT_ALPN,
  DEFAULT_CONNECT_TIMEOUT_MS,
  DEFAULT_MAX_FRAME_SIZE,
  NodeStreamConnection,
  TcpClient,
  TcpServer,
  TlsClient,
  TlsServer,
  assertNativeQuicAvailable,
  decodeEnvelopeFramePayload,
  detectNativeQuic,
  encodeEnvelopeFrame,
  encodeFrame,
  encodeRawMessageFrame,
  tryDecodeFrame,
  validateMaxFrameSize,
  type DecodedFrame,
  type FrameEndian,
  type FrameOptions,
  type NodeStreamConnectionOptions,
  type QuicAvailability,
  type ReceiveOptions,
  type StreamHandler,
  type TcpClientConfig,
  type TcpServerConfig,
  type TlsClientConfig,
  type TlsServerConfig,
} from "./transport/index.js";
export {
  AxcpEnvelopeType,
  ContextPatchType,
  DeltaOpType,
  DeltaOpTypeMessage,
  ErrorCode,
  root,
  toSafeNumber,
  type A2AJsonBlob,
  type AxcpEnvelope,
  type CapabilityAck,
  type CapabilityDescriptor,
  type CapabilityMessage,
  type CapabilityOffer,
  type CapabilityRequest,
  type ContextGraphVersion,
  type ContextPatch,
  type DeltaOp,
  type ErrorMessage,
  type McpJsonBlob,
  type ProfileAck,
  type ProfileNegotiate,
  type RetryEnvelope,
  type RoutePolicyMessage,
  type SyncRequest,
  type SyncSubscribe,
  type SystemStats,
  type TelemetryDatagram,
  type TokenUsage,
  type UInt64Value,
} from "./pb/schema.js";

export const VERSION = "0.1.0";
