export { Agent, type AgentOptions } from "./agent.js";
export {
  DID_AUTH_TRANSCRIPT_VERSION,
  DEFAULT_PROFILE_SECURE_BASELINE,
  DEFAULT_PROTOCOL_VERSION,
  buildAuthTranscript,
  decodeEnvelope,
  encodeEnvelope,
  newEnvelope,
  signEnvelope,
  signingPayload,
  verifyEnvelope,
  type NewEnvelopeOptions,
  type SignEnvelopeOptions,
  type VerifyEnvelopeOptions,
} from "./envelope.js";
export {
  AXCPError,
  DIDError,
  DIDResolutionError,
  DeprecatedProfileError,
  InvalidCapabilitiesError,
  InvalidDIDFormat,
  InvalidEnvelopeError,
  InvalidPrivateKeyError,
  InvalidReplayConfigError,
  KeyMismatchError,
  NegotiationError,
  NoProfileOverlapError,
  NoSignatureAlgorithmOverlapError,
  ReplayDetectedError,
  ReplayError,
  SequenceTooOldError,
  SignatureError,
  SignatureMissingError,
  SignatureVerificationError,
  TimestampError,
  TimestampExpiredError,
  TimestampFutureError,
  TimestampMissingError,
} from "./errors.js";
export {
  DID,
  DID_KEY_ED25519_MULTICODEC_PREFIX,
  ED25519_PRIVATE_SEED_SIZE,
  ED25519_PUBLIC_KEY_SIZE,
  ED25519_SIGNATURE_SIZE,
  Identity,
  InMemoryDIDResolver,
  didKeyFromPublicKey,
  publicKeyFromDidKey,
  resolveEd25519PublicKey,
  verifySignature,
  type DIDDocument,
  type DIDResolver,
  type IdentityJson,
  type ParsedDID,
  type PublicKeyRecord,
} from "./identity.js";
export {
  DEFAULT_CAPABILITIES,
  DEFAULT_CLIENT_HELLO,
  PROTOCOL_VERSION_V1,
  Profile,
  SIG_ALGO_ED25519,
  negotiate,
  type Capabilities,
  type ClientHello,
  type NegotiateOptions,
  type ServerHello,
} from "./profile.js";
export { ReplayProtector, type ReplayProtectorOptions } from "./replay.js";
export {
  DEFAULT_CLOCK_SKEW_MS,
  DEFAULT_MAX_TIMESTAMP_AGE_MS,
  TimestampValidator,
  dateFromMs,
  nowMs,
  rfc3339SecondsFromMs,
  type TimestampValidatorOptions,
} from "./timestamp.js";
export {
  AxcpEnvelopeType,
  ContextPatchType,
  DeltaOpType,
  DeltaOpTypeMessage,
  ErrorCode,
  root,
  toSafeNumber,
  type A2AJsonBlob,
  type AxcpEnvelope,
  type CapabilityAck,
  type CapabilityDescriptor,
  type CapabilityMessage,
  type CapabilityOffer,
  type CapabilityRequest,
  type ContextGraphVersion,
  type ContextPatch,
  type DeltaOp,
  type ErrorMessage,
  type McpJsonBlob,
  type ProfileAck,
  type ProfileNegotiate,
  type RetryEnvelope,
  type RoutePolicyMessage,
  type SyncRequest,
  type SyncSubscribe,
  type SystemStats,
  type TelemetryDatagram,
  type TokenUsage,
  type UInt64Value,
} from "./pb/schema.js";

export const VERSION = "0.1.0";
