apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enterprise-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "enterprise-node.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enterprise-node.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "enterprise-node.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: enterprise-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config=/etc/axcp/enterprise.yaml"
          ports:
            - name: http
              containerPort: 7143
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/axcp/enterprise.yaml
              subPath: enterprise.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "enterprise-node.fullname" . }}-config
