// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: proto/axcp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKNOWN                     ErrorCode = 0
	ErrorCode_INVALID_CONTEXT             ErrorCode = 1
	ErrorCode_UNAUTHORIZED                ErrorCode = 2
	ErrorCode_TOOL_NOT_FOUND              ErrorCode = 3
	ErrorCode_TIMEOUT                     ErrorCode = 4
	ErrorCode_UNSUPPORTED_VERSION         ErrorCode = 5
	ErrorCode_BAD_DELTA                   ErrorCode = 6
	ErrorCode_PAYLOAD_TOO_LARGE           ErrorCode = 7
	ErrorCode_MALFORMED_REQUEST           ErrorCode = 8
	ErrorCode_TOO_MANY_REQUESTS           ErrorCode = 9
	ErrorCode_PROFILE_MISMATCH            ErrorCode = 12
	ErrorCode_PROFILE_UNSUPPORTED         ErrorCode = 13
	ErrorCode_PROFILE_NEGOTIATION_FAILED  ErrorCode = 14
	ErrorCode_MISSING_PATCH_RANGE         ErrorCode = 15
	ErrorCode_DP_POLICY_CONFLICT          ErrorCode = 16
)

type DpMechanism int32

const (
	DpMechanism_LAPLACE  DpMechanism = 0
	DpMechanism_GAUSSIAN DpMechanism = 1
)

type DpParams_Granularity int32

const (
	DpParams_RECORD DpParams_Granularity = 0
	DpParams_BATCH  DpParams_Granularity = 1
	DpParams_TOKEN  DpParams_Granularity = 2
)

// Basic message types
type AxcpEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       uint32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TraceId       string                  `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Profile       uint32                  `protobuf:"varint,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Payload       isAxcpEnvelope_Payload  `protobuf_oneof:"payload"`
	Signature     []byte                  `protobuf:"bytes,100,opt,name=signature,proto3" json:"signature,omitempty"`
	AttestationProof []byte               `protobuf:"bytes,101,opt,name=attestation_proof,json=attestationProof,proto3" json:"attestation_proof,omitempty"`
}

type isAxcpEnvelope_Payload interface {
	isAxcpEnvelope_Payload()
}

type AxcpEnvelope_ContextPatch struct {
	ContextPatch *ContextPatch `protobuf:"bytes,4,opt,name=context_patch,json=contextPatch,proto3,oneof"`
}

type AxcpEnvelope_CapabilityMsg struct {
	CapabilityMsg *CapabilityMessage `protobuf:"bytes,5,opt,name=capability_msg,json=capabilityMsg,proto3,oneof"`
}

type AxcpEnvelope_RouteMsg struct {
	RouteMsg *RoutePolicyMessage `protobuf:"bytes,6,opt,name=route_msg,json=routeMsg,proto3,oneof"`
}

type AxcpEnvelope_Error struct {
	Error *ErrorMessage `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type AxcpEnvelope_ProfileNeg struct {
	ProfileNeg *ProfileNegotiate `protobuf:"bytes,8,opt,name=profile_neg,json=profileNeg,proto3,oneof"`
}

type AxcpEnvelope_ProfileAck struct {
	ProfileAck *ProfileAck `protobuf:"bytes,9,opt,name=profile_ack,json=profileAck,proto3,oneof"`
}

type AxcpEnvelope_RetryEnv struct {
	RetryEnv *RetryEnvelope `protobuf:"bytes,10,opt,name=retry_env,json=retryEnv,proto3,oneof"`
}

type AxcpEnvelope_Telemetry struct {
	Telemetry *TelemetryDatagram `protobuf:"bytes,11,opt,name=telemetry,proto3,oneof"`
}

func (*AxcpEnvelope_ContextPatch) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_CapabilityMsg) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_RouteMsg) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_Error) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_ProfileNeg) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_ProfileAck) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_RetryEnv) isAxcpEnvelope_Payload() {}
func (*AxcpEnvelope_Telemetry) isAxcpEnvelope_Payload() {}

func (x *AxcpEnvelope) Reset() {
	*x = AxcpEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AxcpEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AxcpEnvelope) ProtoMessage() {}

func (x *AxcpEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AxcpEnvelope.ProtoReflect.Descriptor instead.
func (*AxcpEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{0}
}

func (x *AxcpEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AxcpEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AxcpEnvelope) GetProfile() uint32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (m *AxcpEnvelope) GetPayload() isAxcpEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *AxcpEnvelope) GetContextPatch() *ContextPatch {
	if x, ok := x.GetPayload().(*AxcpEnvelope_ContextPatch); ok {
		return x.ContextPatch
	}
	return nil
}

func (x *AxcpEnvelope) GetCapabilityMsg() *CapabilityMessage {
	if x, ok := x.GetPayload().(*AxcpEnvelope_CapabilityMsg); ok {
		return x.CapabilityMsg
	}
	return nil
}

func (x *AxcpEnvelope) GetRouteMsg() *RoutePolicyMessage {
	if x, ok := x.GetPayload().(*AxcpEnvelope_RouteMsg); ok {
		return x.RouteMsg
	}
	return nil
}

func (x *AxcpEnvelope) GetError() *ErrorMessage {
	if x, ok := x.GetPayload().(*AxcpEnvelope_Error); ok {
		return x.Error
	}
	return nil
}

func (x *AxcpEnvelope) GetProfileNeg() *ProfileNegotiate {
	if x, ok := x.GetPayload().(*AxcpEnvelope_ProfileNeg); ok {
		return x.ProfileNeg
	}
	return nil
}

func (x *AxcpEnvelope) GetProfileAck() *ProfileAck {
	if x, ok := x.GetPayload().(*AxcpEnvelope_ProfileAck); ok {
		return x.ProfileAck
	}
	return nil
}

func (x *AxcpEnvelope) GetRetryEnv() *RetryEnvelope {
	if x, ok := x.GetPayload().(*AxcpEnvelope_RetryEnv); ok {
		return x.RetryEnv
	}
	return nil
}

func (x *AxcpEnvelope) GetTelemetry() *TelemetryDatagram {
	if x, ok := x.GetPayload().(*AxcpEnvelope_Telemetry); ok {
		return x.Telemetry
	}
	return nil
}

func (x *AxcpEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AxcpEnvelope) GetAttestationProof() []byte {
	if x != nil {
		return x.AttestationProof
	}
	return nil
}

// Capability types
type CapabilityDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolId            string     `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	InputSchema       string     `protobuf:"bytes,2,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema      string     `protobuf:"bytes,3,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	TimeoutMs         uint32     `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ResourceHint      string     `protobuf:"bytes,5,opt,name=resource_hint,json=resourceHint,proto3" json:"resource_hint,omitempty"`
	AuthScope         []string   `protobuf:"bytes,6,rep,name=auth_scope,json=authScope,proto3" json:"auth_scope,omitempty"`
	DescriptorVersion string     `protobuf:"bytes,7,opt,name=descriptor_version,json=descriptorVersion,proto3" json:"descriptor_version,omitempty"`
	Dp                *DpParams  `protobuf:"bytes,8,opt,name=dp,proto3" json:"dp,omitempty"`
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityDescriptor) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *CapabilityDescriptor) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *CapabilityDescriptor) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *CapabilityDescriptor) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CapabilityDescriptor) GetResourceHint() string {
	if x != nil {
		return x.ResourceHint
	}
	return ""
}

func (x *CapabilityDescriptor) GetAuthScope() []string {
	if x != nil {
		return x.AuthScope
	}
	return nil
}

func (x *CapabilityDescriptor) GetDescriptorVersion() string {
	if x != nil {
		return x.DescriptorVersion
	}
	return ""
}

func (x *CapabilityDescriptor) GetDp() *DpParams {
	if x != nil {
		return x.Dp
	}
	return nil
}

type CapabilityOffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desc *CapabilityDescriptor `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *CapabilityOffer) Reset() {
	*x = CapabilityOffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityOffer) ProtoMessage() {}

func (x *CapabilityOffer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityOffer.ProtoReflect.Descriptor instead.
func (*CapabilityOffer) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityOffer) GetDesc() *CapabilityDescriptor {
	if x != nil {
		return x.Desc
	}
	return nil
}

type CapabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilityRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CapabilityAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted []string `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *CapabilityAck) Reset() {
	*x = CapabilityAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityAck) ProtoMessage() {}

func (x *CapabilityAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityAck.ProtoReflect.Descriptor instead.
func (*CapabilityAck) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityAck) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

type CapabilityMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind isCapabilityMessage_Kind `protobuf_oneof:"kind"`
}

type isCapabilityMessage_Kind interface {
	isCapabilityMessage_Kind()
}

type CapabilityMessage_Offer struct {
	Offer *CapabilityOffer `protobuf:"bytes,1,opt,name=offer,proto3,oneof"`
}

type CapabilityMessage_Request struct {
	Request *CapabilityRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type CapabilityMessage_Ack struct {
	Ack *CapabilityAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*CapabilityMessage_Offer) isCapabilityMessage_Kind() {}

func (*CapabilityMessage_Request) isCapabilityMessage_Kind() {}

func (*CapabilityMessage_Ack) isCapabilityMessage_Kind() {}

func (x *CapabilityMessage) Reset() {
	*x = CapabilityMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapabilityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityMessage) ProtoMessage() {}

func (x *CapabilityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityMessage.ProtoReflect.Descriptor instead.
func (*CapabilityMessage) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{5}
}

func (m *CapabilityMessage) GetKind() isCapabilityMessage_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *CapabilityMessage) GetOffer() *CapabilityOffer {
	if x, ok := x.GetKind().(*CapabilityMessage_Offer); ok {
		return x.Offer
	}
	return nil
}

func (x *CapabilityMessage) GetRequest() *CapabilityRequest {
	if x, ok := x.GetKind().(*CapabilityMessage_Request); ok {
		return x.Request
	}
	return nil
}

func (x *CapabilityMessage) GetAck() *CapabilityAck {
	if x, ok := x.GetKind().(*CapabilityMessage_Ack); ok {
		return x.Ack
	}
	return nil
}

// Telemetry types
type TelemetryDatagram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampMs uint64                   `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Payload     isTelemetryDatagram_Payload `protobuf_oneof:"payload"`
}

type isTelemetryDatagram_Payload interface {
	isTelemetryDatagram_Payload()
}

type TelemetryDatagram_System struct {
	System *SystemStats `protobuf:"bytes,10,opt,name=system,proto3,oneof"`
}

type TelemetryDatagram_Tokens struct {
	Tokens *TokenUsage `protobuf:"bytes,11,opt,name=tokens,proto3,oneof"`
}

func (*TelemetryDatagram_System) isTelemetryDatagram_Payload() {}

func (*TelemetryDatagram_Tokens) isTelemetryDatagram_Payload() {}

func (x *TelemetryDatagram) Reset() {
	*x = TelemetryDatagram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryDatagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryDatagram) ProtoMessage() {}

func (x *TelemetryDatagram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryDatagram.ProtoReflect.Descriptor instead.
func (*TelemetryDatagram) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryDatagram) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (m *TelemetryDatagram) GetPayload() isTelemetryDatagram_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *TelemetryDatagram) GetSystem() *SystemStats {
	if x, ok := x.GetPayload().(*TelemetryDatagram_System); ok {
		return x.System
	}
	return nil
}

func (x *TelemetryDatagram) GetTokens() *TokenUsage {
	if x, ok := x.GetPayload().(*TelemetryDatagram_Tokens); ok {
		return x.Tokens
	}
	return nil
}

type SystemStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuPercent   uint32 `protobuf:"varint,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes     uint64 `protobuf:"varint,2,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	TemperatureC uint32 `protobuf:"varint,3,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{7}
}

func (x *SystemStats) GetCpuPercent() uint32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemStats) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *SystemStats) GetTemperatureC() uint32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

type TokenUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromptTokens     uint32 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_axcp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{8}
}

func (x *TokenUsage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// Stub implementations for other required types
type DeltaOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeltaOp) Reset() {
	*x = DeltaOp{}
}

func (x *DeltaOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaOp) ProtoMessage() {}

func (x *DeltaOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DeltaOp) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{9}
}

type ContextPatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContextPatch) Reset() {
	*x = ContextPatch{}
}

func (x *ContextPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPatch) ProtoMessage() {}

func (x *ContextPatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ContextPatch) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{10}
}

type RoutePolicyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoutePolicyMessage) Reset() {
	*x = RoutePolicyMessage{}
}

func (x *RoutePolicyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyMessage) ProtoMessage() {}

func (x *RoutePolicyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RoutePolicyMessage) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{11}
}

type ErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{12}
}

type ProfileNegotiate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProfileNegotiate) Reset() {
	*x = ProfileNegotiate{}
}

func (x *ProfileNegotiate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileNegotiate) ProtoMessage() {}

func (x *ProfileNegotiate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ProfileNegotiate) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{13}
}

type ProfileAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProfileAck) Reset() {
	*x = ProfileAck{}
}

func (x *ProfileAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileAck) ProtoMessage() {}

func (x *ProfileAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ProfileAck) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{14}
}

type RetryEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetryEnvelope) Reset() {
	*x = RetryEnvelope{}
}

func (x *RetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEnvelope) ProtoMessage() {}

func (x *RetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RetryEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{15}
}

type DpParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DpParams) Reset() {
	*x = DpParams{}
}

func (x *DpParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpParams) ProtoMessage() {}

func (x *DpParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axcp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DpParams) Descriptor() ([]byte, []int) {
	return file_proto_axcp_proto_rawDescGZIP(), []int{16}
}

var File_proto_axcp_proto protoreflect.FileDescriptor

var file_proto_axcp_proto_rawDescGZIP = func() []byte {
	return []byte{0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
}

var file_proto_axcp_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_axcp_proto_goTypes = []interface{}{
	(*AxcpEnvelope)(nil),          // 0
	(*CapabilityDescriptor)(nil),  // 1
	(*CapabilityOffer)(nil),       // 2
	(*CapabilityRequest)(nil),     // 3
	(*CapabilityAck)(nil),         // 4
	(*CapabilityMessage)(nil),     // 5
	(*TelemetryDatagram)(nil),     // 6
	(*SystemStats)(nil),           // 7
	(*TokenUsage)(nil),            // 8
	(*DeltaOp)(nil),               // 9
	(*ContextPatch)(nil),          // 10
	(*RoutePolicyMessage)(nil),    // 11
	(*ErrorMessage)(nil),          // 12
	(*ProfileNegotiate)(nil),      // 13
	(*ProfileAck)(nil),            // 14
	(*RetryEnvelope)(nil),         // 15
	(*DpParams)(nil),              // 16
}

var file_proto_axcp_proto_depIdxs = []int32{
	10,  // 0: AxcpEnvelope.context_patch:type_name -> ContextPatch
	5,   // 1: AxcpEnvelope.capability_msg:type_name -> CapabilityMessage
	11,  // 2: AxcpEnvelope.route_msg:type_name -> RoutePolicyMessage
	12,  // 3: AxcpEnvelope.error:type_name -> ErrorMessage
	13,  // 4: AxcpEnvelope.profile_neg:type_name -> ProfileNegotiate
	14,  // 5: AxcpEnvelope.profile_ack:type_name -> ProfileAck
	15,  // 6: AxcpEnvelope.retry_env:type_name -> RetryEnvelope
	6,   // 7: AxcpEnvelope.telemetry:type_name -> TelemetryDatagram
	16,  // 8: CapabilityDescriptor.dp:type_name -> DpParams
	1,   // 9: CapabilityOffer.desc:type_name -> CapabilityDescriptor
	2,   // 10: CapabilityMessage.offer:type_name -> CapabilityOffer
	3,   // 11: CapabilityMessage.request:type_name -> CapabilityRequest
	4,   // 12: CapabilityMessage.ack:type_name -> CapabilityAck
	7,   // 13: TelemetryDatagram.system:type_name -> SystemStats
	8,   // 14: TelemetryDatagram.tokens:type_name -> TokenUsage
	15,  // [15:15] is the sub-list for method output_type
	15,  // [15:15] is the sub-list for method input_type
	15,  // [15:15] is the sub-list for extension type_name
	15,  // [15:15] is the sub-list for extension extendee
	0,   // [0:15] is the sub-list for field type_name
}

func init() { file_proto_axcp_proto_init() }
func file_proto_axcp_proto_init() {
	if File_proto_axcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_axcp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AxcpEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityOffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapabilityMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryDatagram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeltaOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextPatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutePolicyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileNegotiate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetryEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_axcp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DpParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_axcp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AxcpEnvelope_ContextPatch)(nil),
		(*AxcpEnvelope_CapabilityMsg)(nil),
		(*AxcpEnvelope_RouteMsg)(nil),
		(*AxcpEnvelope_Error)(nil),
		(*AxcpEnvelope_ProfileNeg)(nil),
		(*AxcpEnvelope_ProfileAck)(nil),
		(*AxcpEnvelope_RetryEnv)(nil),
		(*AxcpEnvelope_Telemetry)(nil),
	}
	file_proto_axcp_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CapabilityMessage_Offer)(nil),
		(*CapabilityMessage_Request)(nil),
		(*CapabilityMessage_Ack)(nil),
	}
	file_proto_axcp_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*TelemetryDatagram_System)(nil),
		(*TelemetryDatagram_Tokens)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_axcp_proto_rawDescGZIP(),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_axcp_proto_goTypes,
		DependencyIndexes: file_proto_axcp_proto_depIdxs,
		MessageInfos:      file_proto_axcp_proto_msgTypes,
	}.Build()
	File_proto_axcp_proto = out.File
	file_proto_axcp_proto_rawDescGZIP = nil
	file_proto_axcp_proto_goTypes = nil
	file_proto_axcp_proto_depIdxs = nil
}