// © 2025 TradePhantom LLC – BSL 1.1 / Apache-2.0 fallback

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: axcp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DpMechanism int32

const (
	DpMechanism_LAPLACE  DpMechanism = 0
	DpMechanism_GAUSSIAN DpMechanism = 1
)

// Enum value maps for DpMechanism.
var (
	DpMechanism_name = map[int32]string{
		0: "LAPLACE",
		1: "GAUSSIAN",
	}
	DpMechanism_value = map[string]int32{
		"LAPLACE":  0,
		"GAUSSIAN": 1,
	}
)

func (x DpMechanism) Enum() *DpMechanism {
	p := new(DpMechanism)
	*p = x
	return p
}

func (x DpMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DpMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_axcp_proto_enumTypes[0].Descriptor()
}

func (DpMechanism) Type() protoreflect.EnumType {
	return &file_axcp_proto_enumTypes[0]
}

func (x DpMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DpMechanism.Descriptor instead.
func (DpMechanism) EnumDescriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_UNKNOWN                    ErrorCode = 0
	ErrorCode_INVALID_CONTEXT            ErrorCode = 1
	ErrorCode_UNAUTHORIZED               ErrorCode = 2
	ErrorCode_TOOL_NOT_FOUND             ErrorCode = 3
	ErrorCode_TIMEOUT                    ErrorCode = 4
	ErrorCode_UNSUPPORTED_VERSION        ErrorCode = 5
	ErrorCode_BAD_DELTA                  ErrorCode = 6
	ErrorCode_PAYLOAD_TOO_LARGE          ErrorCode = 7
	ErrorCode_MALFORMED_REQUEST          ErrorCode = 8
	ErrorCode_TOO_MANY_REQUESTS          ErrorCode = 9
	ErrorCode_PROFILE_MISMATCH           ErrorCode = 12
	ErrorCode_PROFILE_UNSUPPORTED        ErrorCode = 13
	ErrorCode_PROFILE_NEGOTIATION_FAILED ErrorCode = 14
	ErrorCode_MISSING_PATCH_RANGE        ErrorCode = 15
	ErrorCode_DP_POLICY_CONFLICT         ErrorCode = 16
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "INVALID_CONTEXT",
		2:  "UNAUTHORIZED",
		3:  "TOOL_NOT_FOUND",
		4:  "TIMEOUT",
		5:  "UNSUPPORTED_VERSION",
		6:  "BAD_DELTA",
		7:  "PAYLOAD_TOO_LARGE",
		8:  "MALFORMED_REQUEST",
		9:  "TOO_MANY_REQUESTS",
		12: "PROFILE_MISMATCH",
		13: "PROFILE_UNSUPPORTED",
		14: "PROFILE_NEGOTIATION_FAILED",
		15: "MISSING_PATCH_RANGE",
		16: "DP_POLICY_CONFLICT",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":                    0,
		"INVALID_CONTEXT":            1,
		"UNAUTHORIZED":               2,
		"TOOL_NOT_FOUND":             3,
		"TIMEOUT":                    4,
		"UNSUPPORTED_VERSION":        5,
		"BAD_DELTA":                  6,
		"PAYLOAD_TOO_LARGE":          7,
		"MALFORMED_REQUEST":          8,
		"TOO_MANY_REQUESTS":          9,
		"PROFILE_MISMATCH":           12,
		"PROFILE_UNSUPPORTED":        13,
		"PROFILE_NEGOTIATION_FAILED": 14,
		"MISSING_PATCH_RANGE":        15,
		"DP_POLICY_CONFLICT":         16,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_axcp_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_axcp_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{1}
}

type DeltaOp_OpType int32

const (
	DeltaOp_ADD     DeltaOp_OpType = 0
	DeltaOp_REPLACE DeltaOp_OpType = 1
	DeltaOp_REMOVE  DeltaOp_OpType = 2
	DeltaOp_MERGE   DeltaOp_OpType = 3
)

// Enum value maps for DeltaOp_OpType.
var (
	DeltaOp_OpType_name = map[int32]string{
		0: "ADD",
		1: "REPLACE",
		2: "REMOVE",
		3: "MERGE",
	}
	DeltaOp_OpType_value = map[string]int32{
		"ADD":     0,
		"REPLACE": 1,
		"REMOVE":  2,
		"MERGE":   3,
	}
)

func (x DeltaOp_OpType) Enum() *DeltaOp_OpType {
	p := new(DeltaOp_OpType)
	*p = x
	return p
}

func (x DeltaOp_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeltaOp_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_axcp_proto_enumTypes[2].Descriptor()
}

func (DeltaOp_OpType) Type() protoreflect.EnumType {
	return &file_axcp_proto_enumTypes[2]
}

func (x DeltaOp_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeltaOp_OpType.Descriptor instead.
func (DeltaOp_OpType) EnumDescriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{1, 0}
}

type DpParams_Granularity int32

const (
	DpParams_RECORD DpParams_Granularity = 0
	DpParams_BATCH  DpParams_Granularity = 1
	DpParams_TOKEN  DpParams_Granularity = 2
)

// Enum value maps for DpParams_Granularity.
var (
	DpParams_Granularity_name = map[int32]string{
		0: "RECORD",
		1: "BATCH",
		2: "TOKEN",
	}
	DpParams_Granularity_value = map[string]int32{
		"RECORD": 0,
		"BATCH":  1,
		"TOKEN":  2,
	}
)

func (x DpParams_Granularity) Enum() *DpParams_Granularity {
	p := new(DpParams_Granularity)
	*p = x
	return p
}

func (x DpParams_Granularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DpParams_Granularity) Descriptor() protoreflect.EnumDescriptor {
	return file_axcp_proto_enumTypes[3].Descriptor()
}

func (DpParams_Granularity) Type() protoreflect.EnumType {
	return &file_axcp_proto_enumTypes[3]
}

func (x DpParams_Granularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DpParams_Granularity.Descriptor instead.
func (DpParams_Granularity) EnumDescriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{18, 0}
}

type AxcpEnvelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`               // protocol version (currently 1)
	TraceId string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // request / conversation correlation
	Profile uint32                 `protobuf:"varint,3,opt,name=profile,proto3" json:"profile,omitempty"`               // 0 = Basic … 3 = Enterprise-Privacy
	// Types that are valid to be assigned to Payload:
	//
	//	*AxcpEnvelope_ContextPatch
	//	*AxcpEnvelope_CapabilityMsg
	//	*AxcpEnvelope_RouteMsg
	//	*AxcpEnvelope_Error
	//	*AxcpEnvelope_ProfileNeg
	//	*AxcpEnvelope_ProfileAck
	//	*AxcpEnvelope_RetryEnv
	//	*AxcpEnvelope_Telemetry
	Payload          isAxcpEnvelope_Payload `protobuf_oneof:"payload"`
	Signature        []byte                 `protobuf:"bytes,100,opt,name=signature,proto3" json:"signature,omitempty"`                                       // detached sig (profile ≥1)
	AttestationProof []byte                 `protobuf:"bytes,101,opt,name=attestation_proof,json=attestationProof,proto3" json:"attestation_proof,omitempty"` // SGX / SEV quote (profile ≥2)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AxcpEnvelope) Reset() {
	*x = AxcpEnvelope{}
	mi := &file_axcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AxcpEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AxcpEnvelope) ProtoMessage() {}

func (x *AxcpEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AxcpEnvelope.ProtoReflect.Descriptor instead.
func (*AxcpEnvelope) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{0}
}

func (x *AxcpEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AxcpEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AxcpEnvelope) GetProfile() uint32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *AxcpEnvelope) GetPayload() isAxcpEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AxcpEnvelope) GetContextPatch() *ContextPatch {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_ContextPatch); ok {
			return x.ContextPatch
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetCapabilityMsg() *CapabilityMessage {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_CapabilityMsg); ok {
			return x.CapabilityMsg
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetRouteMsg() *RoutePolicyMessage {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_RouteMsg); ok {
			return x.RouteMsg
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetProfileNeg() *ProfileNegotiate {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_ProfileNeg); ok {
			return x.ProfileNeg
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetProfileAck() *ProfileAck {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_ProfileAck); ok {
			return x.ProfileAck
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetRetryEnv() *RetryEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_RetryEnv); ok {
			return x.RetryEnv
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetTelemetry() *TelemetryDatagram {
	if x != nil {
		if x, ok := x.Payload.(*AxcpEnvelope_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *AxcpEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AxcpEnvelope) GetAttestationProof() []byte {
	if x != nil {
		return x.AttestationProof
	}
	return nil
}

type isAxcpEnvelope_Payload interface {
	isAxcpEnvelope_Payload()
}

type AxcpEnvelope_ContextPatch struct {
	ContextPatch *ContextPatch `protobuf:"bytes,4,opt,name=context_patch,json=contextPatch,proto3,oneof"`
}

type AxcpEnvelope_CapabilityMsg struct {
	CapabilityMsg *CapabilityMessage `protobuf:"bytes,5,opt,name=capability_msg,json=capabilityMsg,proto3,oneof"`
}

type AxcpEnvelope_RouteMsg struct {
	RouteMsg *RoutePolicyMessage `protobuf:"bytes,6,opt,name=route_msg,json=routeMsg,proto3,oneof"`
}

type AxcpEnvelope_Error struct {
	Error *ErrorMessage `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type AxcpEnvelope_ProfileNeg struct {
	ProfileNeg *ProfileNegotiate `protobuf:"bytes,8,opt,name=profile_neg,json=profileNeg,proto3,oneof"` // QUIC capability handshake
}

type AxcpEnvelope_ProfileAck struct {
	ProfileAck *ProfileAck `protobuf:"bytes,9,opt,name=profile_ack,json=profileAck,proto3,oneof"`
}

type AxcpEnvelope_RetryEnv struct {
	RetryEnv *RetryEnvelope `protobuf:"bytes,10,opt,name=retry_env,json=retryEnv,proto3,oneof"` // store-and-forward batch
}

type AxcpEnvelope_Telemetry struct {
	Telemetry *TelemetryDatagram `protobuf:"bytes,11,opt,name=telemetry,proto3,oneof"` // QUIC DATAGRAM
}

func (*AxcpEnvelope_ContextPatch) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_CapabilityMsg) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_RouteMsg) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_Error) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_ProfileNeg) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_ProfileAck) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_RetryEnv) isAxcpEnvelope_Payload() {}

func (*AxcpEnvelope_Telemetry) isAxcpEnvelope_Payload() {}

type DeltaOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            DeltaOp_OpType         `protobuf:"varint,1,opt,name=op,proto3,enum=axcp.v0_1.DeltaOp_OpType" json:"op,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // JSON Pointer
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // gz-compressed payload
	Ts            uint64                 `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`    // lamport / microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaOp) Reset() {
	*x = DeltaOp{}
	mi := &file_axcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaOp) ProtoMessage() {}

func (x *DeltaOp) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaOp.ProtoReflect.Descriptor instead.
func (*DeltaOp) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{1}
}

func (x *DeltaOp) GetOp() DeltaOp_OpType {
	if x != nil {
		return x.Op
	}
	return DeltaOp_ADD
}

func (x *DeltaOp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeltaOp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeltaOp) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ContextPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	BaseVersion   uint64                 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	Ops           []*DeltaOp             `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPatch) Reset() {
	*x = ContextPatch{}
	mi := &file_axcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPatch) ProtoMessage() {}

func (x *ContextPatch) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPatch.ProtoReflect.Descriptor instead.
func (*ContextPatch) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{2}
}

func (x *ContextPatch) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ContextPatch) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *ContextPatch) GetOps() []*DeltaOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type ContextGraphVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextGraphVersion) Reset() {
	*x = ContextGraphVersion{}
	mi := &file_axcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextGraphVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextGraphVersion) ProtoMessage() {}

func (x *ContextGraphVersion) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextGraphVersion.ProtoReflect.Descriptor instead.
func (*ContextGraphVersion) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{3}
}

func (x *ContextGraphVersion) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ContextGraphVersion) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncSubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *ContextGraphVersion   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSubscribe) Reset() {
	*x = SyncSubscribe{}
	mi := &file_axcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSubscribe) ProtoMessage() {}

func (x *SyncSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSubscribe.ProtoReflect.Descriptor instead.
func (*SyncSubscribe) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{4}
}

func (x *SyncSubscribe) GetFrom() *ContextGraphVersion {
	if x != nil {
		return x.From
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissingFrom   *ContextGraphVersion   `protobuf:"bytes,1,opt,name=missing_from,json=missingFrom,proto3" json:"missing_from,omitempty"`
	ToVersion     uint64                 `protobuf:"varint,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_axcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{5}
}

func (x *SyncRequest) GetMissingFrom() *ContextGraphVersion {
	if x != nil {
		return x.MissingFrom
	}
	return nil
}

func (x *SyncRequest) GetToVersion() uint64 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

type RetryEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BufferedPatches []*ContextPatch        `protobuf:"bytes,1,rep,name=buffered_patches,json=bufferedPatches,proto3" json:"buffered_patches,omitempty"`
	TtlMs           uint32                 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryEnvelope) Reset() {
	*x = RetryEnvelope{}
	mi := &file_axcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEnvelope) ProtoMessage() {}

func (x *RetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEnvelope.ProtoReflect.Descriptor instead.
func (*RetryEnvelope) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{6}
}

func (x *RetryEnvelope) GetBufferedPatches() []*ContextPatch {
	if x != nil {
		return x.BufferedPatches
	}
	return nil
}

func (x *RetryEnvelope) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type CapabilityOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desc          *CapabilityDescriptor  `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityOffer) Reset() {
	*x = CapabilityOffer{}
	mi := &file_axcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityOffer) ProtoMessage() {}

func (x *CapabilityOffer) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityOffer.ProtoReflect.Descriptor instead.
func (*CapabilityOffer) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityOffer) GetDesc() *CapabilityDescriptor {
	if x != nil {
		return x.Desc
	}
	return nil
}

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_axcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CapabilityAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []string               `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityAck) Reset() {
	*x = CapabilityAck{}
	mi := &file_axcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityAck) ProtoMessage() {}

func (x *CapabilityAck) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityAck.ProtoReflect.Descriptor instead.
func (*CapabilityAck) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{9}
}

func (x *CapabilityAck) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

type CapabilityMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*CapabilityMessage_Offer
	//	*CapabilityMessage_Request
	//	*CapabilityMessage_Ack
	Kind          isCapabilityMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityMessage) Reset() {
	*x = CapabilityMessage{}
	mi := &file_axcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityMessage) ProtoMessage() {}

func (x *CapabilityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityMessage.ProtoReflect.Descriptor instead.
func (*CapabilityMessage) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{10}
}

func (x *CapabilityMessage) GetKind() isCapabilityMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *CapabilityMessage) GetOffer() *CapabilityOffer {
	if x != nil {
		if x, ok := x.Kind.(*CapabilityMessage_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *CapabilityMessage) GetRequest() *CapabilityRequest {
	if x != nil {
		if x, ok := x.Kind.(*CapabilityMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *CapabilityMessage) GetAck() *CapabilityAck {
	if x != nil {
		if x, ok := x.Kind.(*CapabilityMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isCapabilityMessage_Kind interface {
	isCapabilityMessage_Kind()
}

type CapabilityMessage_Offer struct {
	Offer *CapabilityOffer `protobuf:"bytes,1,opt,name=offer,proto3,oneof"`
}

type CapabilityMessage_Request struct {
	Request *CapabilityRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type CapabilityMessage_Ack struct {
	Ack *CapabilityAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*CapabilityMessage_Offer) isCapabilityMessage_Kind() {}

func (*CapabilityMessage_Request) isCapabilityMessage_Kind() {}

func (*CapabilityMessage_Ack) isCapabilityMessage_Kind() {}

type CapabilityDescriptor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ToolId            string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	InputSchema       string                 `protobuf:"bytes,2,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema      string                 `protobuf:"bytes,3,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	TimeoutMs         uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ResourceHint      string                 `protobuf:"bytes,5,opt,name=resource_hint,json=resourceHint,proto3" json:"resource_hint,omitempty"`
	AuthScope         []string               `protobuf:"bytes,6,rep,name=auth_scope,json=authScope,proto3" json:"auth_scope,omitempty"`
	DescriptorVersion string                 `protobuf:"bytes,7,opt,name=descriptor_version,json=descriptorVersion,proto3" json:"descriptor_version,omitempty"`
	Dp                *DpParams              `protobuf:"bytes,8,opt,name=dp,proto3" json:"dp,omitempty"` // profile ≥3
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_axcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilityDescriptor) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *CapabilityDescriptor) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *CapabilityDescriptor) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *CapabilityDescriptor) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CapabilityDescriptor) GetResourceHint() string {
	if x != nil {
		return x.ResourceHint
	}
	return ""
}

func (x *CapabilityDescriptor) GetAuthScope() []string {
	if x != nil {
		return x.AuthScope
	}
	return nil
}

func (x *CapabilityDescriptor) GetDescriptorVersion() string {
	if x != nil {
		return x.DescriptorVersion
	}
	return ""
}

func (x *CapabilityDescriptor) GetDp() *DpParams {
	if x != nil {
		return x.Dp
	}
	return nil
}

type ProfileNegotiate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupportedMask uint32                 `protobuf:"varint,1,opt,name=supported_mask,json=supportedMask,proto3" json:"supported_mask,omitempty"` // bitmask; bit0=Profile-0 …
	MinRequired   uint32                 `protobuf:"varint,2,opt,name=min_required,json=minRequired,proto3" json:"min_required,omitempty"`       // lowest acceptable profile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileNegotiate) Reset() {
	*x = ProfileNegotiate{}
	mi := &file_axcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileNegotiate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileNegotiate) ProtoMessage() {}

func (x *ProfileNegotiate) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileNegotiate.ProtoReflect.Descriptor instead.
func (*ProfileNegotiate) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{12}
}

func (x *ProfileNegotiate) GetSupportedMask() uint32 {
	if x != nil {
		return x.SupportedMask
	}
	return 0
}

func (x *ProfileNegotiate) GetMinRequired() uint32 {
	if x != nil {
		return x.MinRequired
	}
	return 0
}

type ProfileAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgreedProfile uint32                 `protobuf:"varint,1,opt,name=agreed_profile,json=agreedProfile,proto3" json:"agreed_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileAck) Reset() {
	*x = ProfileAck{}
	mi := &file_axcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileAck) ProtoMessage() {}

func (x *ProfileAck) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileAck.ProtoReflect.Descriptor instead.
func (*ProfileAck) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{13}
}

func (x *ProfileAck) GetAgreedProfile() uint32 {
	if x != nil {
		return x.AgreedProfile
	}
	return 0
}

type RoutePolicyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	WasmBlob      []byte                 `protobuf:"bytes,2,opt,name=wasm_blob,json=wasmBlob,proto3" json:"wasm_blob,omitempty"`
	TtlMs         uint32                 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicyMessage) Reset() {
	*x = RoutePolicyMessage{}
	mi := &file_axcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyMessage) ProtoMessage() {}

func (x *RoutePolicyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyMessage.ProtoReflect.Descriptor instead.
func (*RoutePolicyMessage) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{14}
}

func (x *RoutePolicyMessage) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *RoutePolicyMessage) GetWasmBlob() []byte {
	if x != nil {
		return x.WasmBlob
	}
	return nil
}

func (x *RoutePolicyMessage) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type SystemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    uint32                 `protobuf:"varint,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes      uint64                 `protobuf:"varint,2,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	TemperatureC  uint32                 `protobuf:"varint,3,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_axcp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{15}
}

func (x *SystemStats) GetCpuPercent() uint32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemStats) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *SystemStats) GetTemperatureC() uint32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     uint32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_axcp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{16}
}

func (x *TokenUsage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type TelemetryDatagram struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs uint64                 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryDatagram_System
	//	*TelemetryDatagram_Tokens
	Payload       isTelemetryDatagram_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryDatagram) Reset() {
	*x = TelemetryDatagram{}
	mi := &file_axcp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryDatagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryDatagram) ProtoMessage() {}

func (x *TelemetryDatagram) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryDatagram.ProtoReflect.Descriptor instead.
func (*TelemetryDatagram) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{17}
}

func (x *TelemetryDatagram) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TelemetryDatagram) GetPayload() isTelemetryDatagram_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryDatagram) GetSystem() *SystemStats {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryDatagram_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *TelemetryDatagram) GetTokens() *TokenUsage {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryDatagram_Tokens); ok {
			return x.Tokens
		}
	}
	return nil
}

type isTelemetryDatagram_Payload interface {
	isTelemetryDatagram_Payload()
}

type TelemetryDatagram_System struct {
	System *SystemStats `protobuf:"bytes,10,opt,name=system,proto3,oneof"`
}

type TelemetryDatagram_Tokens struct {
	Tokens *TokenUsage `protobuf:"bytes,11,opt,name=tokens,proto3,oneof"`
}

func (*TelemetryDatagram_System) isTelemetryDatagram_Payload() {}

func (*TelemetryDatagram_Tokens) isTelemetryDatagram_Payload() {}

type DpParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epsilon       float64                `protobuf:"fixed64,1,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta         float64                `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Mech          DpMechanism            `protobuf:"varint,3,opt,name=mech,proto3,enum=axcp.v0_1.DpMechanism" json:"mech,omitempty"`
	ClipNorm      float64                `protobuf:"fixed64,4,opt,name=clip_norm,json=clipNorm,proto3" json:"clip_norm,omitempty"`
	Gran          DpParams_Granularity   `protobuf:"varint,5,opt,name=gran,proto3,enum=axcp.v0_1.DpParams_Granularity" json:"gran,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DpParams) Reset() {
	*x = DpParams{}
	mi := &file_axcp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpParams) ProtoMessage() {}

func (x *DpParams) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpParams.ProtoReflect.Descriptor instead.
func (*DpParams) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{18}
}

func (x *DpParams) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *DpParams) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *DpParams) GetMech() DpMechanism {
	if x != nil {
		return x.Mech
	}
	return DpMechanism_LAPLACE
}

func (x *DpParams) GetClipNorm() float64 {
	if x != nil {
		return x.ClipNorm
	}
	return 0
}

func (x *DpParams) GetGran() DpParams_Granularity {
	if x != nil {
		return x.Gran
	}
	return DpParams_RECORD
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Diagnostics   []byte                 `protobuf:"bytes,3,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_axcp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorMessage) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorMessage) GetDiagnostics() []byte {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type McpJsonBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpJsonBlob) Reset() {
	*x = McpJsonBlob{}
	mi := &file_axcp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpJsonBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpJsonBlob) ProtoMessage() {}

func (x *McpJsonBlob) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpJsonBlob.ProtoReflect.Descriptor instead.
func (*McpJsonBlob) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{20}
}

func (x *McpJsonBlob) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type A2AJsonBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2AJsonBlob) Reset() {
	*x = A2AJsonBlob{}
	mi := &file_axcp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2AJsonBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2AJsonBlob) ProtoMessage() {}

func (x *A2AJsonBlob) ProtoReflect() protoreflect.Message {
	mi := &file_axcp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2AJsonBlob.ProtoReflect.Descriptor instead.
func (*A2AJsonBlob) Descriptor() ([]byte, []int) {
	return file_axcp_proto_rawDescGZIP(), []int{21}
}

func (x *A2AJsonBlob) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_axcp_proto protoreflect.FileDescriptor

const file_axcp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"axcp.proto\x12\taxcp.v0_1\"\x9a\x05\n" +
	"\fAxcpEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\rR\aprofile\x12>\n" +
	"\rcontext_patch\x18\x04 \x01(\v2\x17.axcp.v0_1.ContextPatchH\x00R\fcontextPatch\x12E\n" +
	"\x0ecapability_msg\x18\x05 \x01(\v2\x1c.axcp.v0_1.CapabilityMessageH\x00R\rcapabilityMsg\x12<\n" +
	"\troute_msg\x18\x06 \x01(\v2\x1d.axcp.v0_1.RoutePolicyMessageH\x00R\brouteMsg\x12/\n" +
	"\x05error\x18\a \x01(\v2\x17.axcp.v0_1.ErrorMessageH\x00R\x05error\x12>\n" +
	"\vprofile_neg\x18\b \x01(\v2\x1b.axcp.v0_1.ProfileNegotiateH\x00R\n" +
	"profileNeg\x128\n" +
	"\vprofile_ack\x18\t \x01(\v2\x15.axcp.v0_1.ProfileAckH\x00R\n" +
	"profileAck\x127\n" +
	"\tretry_env\x18\n" +
	" \x01(\v2\x18.axcp.v0_1.RetryEnvelopeH\x00R\bretryEnv\x12<\n" +
	"\ttelemetry\x18\v \x01(\v2\x1c.axcp.v0_1.TelemetryDatagramH\x00R\ttelemetry\x12\x1c\n" +
	"\tsignature\x18d \x01(\fR\tsignature\x12+\n" +
	"\x11attestation_proof\x18e \x01(\fR\x10attestationProofB\t\n" +
	"\apayload\"\xa3\x01\n" +
	"\aDeltaOp\x12)\n" +
	"\x02op\x18\x01 \x01(\x0e2\x19.axcp.v0_1.DeltaOp.OpTypeR\x02op\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x04R\x02ts\"5\n" +
	"\x06OpType\x12\a\n" +
	"\x03ADD\x10\x00\x12\v\n" +
	"\aREPLACE\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\x12\t\n" +
	"\x05MERGE\x10\x03\"v\n" +
	"\fContextPatch\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12!\n" +
	"\fbase_version\x18\x02 \x01(\x04R\vbaseVersion\x12$\n" +
	"\x03ops\x18\x03 \x03(\v2\x12.axcp.v0_1.DeltaOpR\x03ops\"N\n" +
	"\x13ContextGraphVersion\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"C\n" +
	"\rSyncSubscribe\x122\n" +
	"\x04from\x18\x01 \x01(\v2\x1e.axcp.v0_1.ContextGraphVersionR\x04from\"o\n" +
	"\vSyncRequest\x12A\n" +
	"\fmissing_from\x18\x01 \x01(\v2\x1e.axcp.v0_1.ContextGraphVersionR\vmissingFrom\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\x04R\ttoVersion\"j\n" +
	"\rRetryEnvelope\x12B\n" +
	"\x10buffered_patches\x18\x01 \x03(\v2\x17.axcp.v0_1.ContextPatchR\x0fbufferedPatches\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\rR\x05ttlMs\"F\n" +
	"\x0fCapabilityOffer\x123\n" +
	"\x04desc\x18\x01 \x01(\v2\x1f.axcp.v0_1.CapabilityDescriptorR\x04desc\"%\n" +
	"\x11CapabilityRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"+\n" +
	"\rCapabilityAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x03(\tR\baccepted\"\xb7\x01\n" +
	"\x11CapabilityMessage\x122\n" +
	"\x05offer\x18\x01 \x01(\v2\x1a.axcp.v0_1.CapabilityOfferH\x00R\x05offer\x128\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.axcp.v0_1.CapabilityRequestH\x00R\arequest\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.axcp.v0_1.CapabilityAckH\x00R\x03ackB\x06\n" +
	"\x04kind\"\xae\x02\n" +
	"\x14CapabilityDescriptor\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12!\n" +
	"\finput_schema\x18\x02 \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x03 \x01(\tR\foutputSchema\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x12#\n" +
	"\rresource_hint\x18\x05 \x01(\tR\fresourceHint\x12\x1d\n" +
	"\n" +
	"auth_scope\x18\x06 \x03(\tR\tauthScope\x12-\n" +
	"\x12descriptor_version\x18\a \x01(\tR\x11descriptorVersion\x12#\n" +
	"\x02dp\x18\b \x01(\v2\x13.axcp.v0_1.DpParamsR\x02dp\"\\\n" +
	"\x10ProfileNegotiate\x12%\n" +
	"\x0esupported_mask\x18\x01 \x01(\rR\rsupportedMask\x12!\n" +
	"\fmin_required\x18\x02 \x01(\rR\vminRequired\"3\n" +
	"\n" +
	"ProfileAck\x12%\n" +
	"\x0eagreed_profile\x18\x01 \x01(\rR\ragreedProfile\"e\n" +
	"\x12RoutePolicyMessage\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1b\n" +
	"\twasm_blob\x18\x02 \x01(\fR\bwasmBlob\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\rR\x05ttlMs\"p\n" +
	"\vSystemStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\rR\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x02 \x01(\x04R\bmemBytes\x12#\n" +
	"\rtemperature_c\x18\x03 \x01(\rR\ftemperatureC\"^\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\rR\x10completionTokens\"\xa4\x01\n" +
	"\x11TelemetryDatagram\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x04R\vtimestampMs\x120\n" +
	"\x06system\x18\n" +
	" \x01(\v2\x16.axcp.v0_1.SystemStatsH\x00R\x06system\x12/\n" +
	"\x06tokens\x18\v \x01(\v2\x15.axcp.v0_1.TokenUsageH\x00R\x06tokensB\t\n" +
	"\apayload\"\xe9\x01\n" +
	"\bDpParams\x12\x18\n" +
	"\aepsilon\x18\x01 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x01R\x05delta\x12*\n" +
	"\x04mech\x18\x03 \x01(\x0e2\x16.axcp.v0_1.DpMechanismR\x04mech\x12\x1b\n" +
	"\tclip_norm\x18\x04 \x01(\x01R\bclipNorm\x123\n" +
	"\x04gran\x18\x05 \x01(\x0e2\x1f.axcp.v0_1.DpParams.GranularityR\x04gran\"/\n" +
	"\vGranularity\x12\n" +
	"\n" +
	"\x06RECORD\x10\x00\x12\t\n" +
	"\x05BATCH\x10\x01\x12\t\n" +
	"\x05TOKEN\x10\x02\"\\\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vdiagnostics\x18\x03 \x01(\fR\vdiagnostics\"!\n" +
	"\vMcpJsonBlob\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"!\n" +
	"\vA2AJsonBlob\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json*(\n" +
	"\vDpMechanism\x12\v\n" +
	"\aLAPLACE\x10\x00\x12\f\n" +
	"\bGAUSSIAN\x10\x01*\xcd\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fINVALID_CONTEXT\x10\x01\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x02\x12\x12\n" +
	"\x0eTOOL_NOT_FOUND\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\x17\n" +
	"\x13UNSUPPORTED_VERSION\x10\x05\x12\r\n" +
	"\tBAD_DELTA\x10\x06\x12\x15\n" +
	"\x11PAYLOAD_TOO_LARGE\x10\a\x12\x15\n" +
	"\x11MALFORMED_REQUEST\x10\b\x12\x15\n" +
	"\x11TOO_MANY_REQUESTS\x10\t\x12\x14\n" +
	"\x10PROFILE_MISMATCH\x10\f\x12\x17\n" +
	"\x13PROFILE_UNSUPPORTED\x10\r\x12\x1e\n" +
	"\x1aPROFILE_NEGOTIATION_FAILED\x10\x0e\x12\x17\n" +
	"\x13MISSING_PATCH_RANGE\x10\x0f\x12\x16\n" +
	"\x12DP_POLICY_CONFLICT\x10\x10B6Z4github.com/tradephantom/axcp-spec/sdk/go/internal/pbb\x06proto3"

var (
	file_axcp_proto_rawDescOnce sync.Once
	file_axcp_proto_rawDescData []byte
)

func file_axcp_proto_rawDescGZIP() []byte {
	file_axcp_proto_rawDescOnce.Do(func() {
		file_axcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_axcp_proto_rawDesc), len(file_axcp_proto_rawDesc)))
	})
	return file_axcp_proto_rawDescData
}

var file_axcp_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_axcp_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_axcp_proto_goTypes = []any{
	(DpMechanism)(0),             // 0: axcp.v0_1.DpMechanism
	(ErrorCode)(0),               // 1: axcp.v0_1.ErrorCode
	(DeltaOp_OpType)(0),          // 2: axcp.v0_1.DeltaOp.OpType
	(DpParams_Granularity)(0),    // 3: axcp.v0_1.DpParams.Granularity
	(*AxcpEnvelope)(nil),         // 4: axcp.v0_1.AxcpEnvelope
	(*DeltaOp)(nil),              // 5: axcp.v0_1.DeltaOp
	(*ContextPatch)(nil),         // 6: axcp.v0_1.ContextPatch
	(*ContextGraphVersion)(nil),  // 7: axcp.v0_1.ContextGraphVersion
	(*SyncSubscribe)(nil),        // 8: axcp.v0_1.SyncSubscribe
	(*SyncRequest)(nil),          // 9: axcp.v0_1.SyncRequest
	(*RetryEnvelope)(nil),        // 10: axcp.v0_1.RetryEnvelope
	(*CapabilityOffer)(nil),      // 11: axcp.v0_1.CapabilityOffer
	(*CapabilityRequest)(nil),    // 12: axcp.v0_1.CapabilityRequest
	(*CapabilityAck)(nil),        // 13: axcp.v0_1.CapabilityAck
	(*CapabilityMessage)(nil),    // 14: axcp.v0_1.CapabilityMessage
	(*CapabilityDescriptor)(nil), // 15: axcp.v0_1.CapabilityDescriptor
	(*ProfileNegotiate)(nil),     // 16: axcp.v0_1.ProfileNegotiate
	(*ProfileAck)(nil),           // 17: axcp.v0_1.ProfileAck
	(*RoutePolicyMessage)(nil),   // 18: axcp.v0_1.RoutePolicyMessage
	(*SystemStats)(nil),          // 19: axcp.v0_1.SystemStats
	(*TokenUsage)(nil),           // 20: axcp.v0_1.TokenUsage
	(*TelemetryDatagram)(nil),    // 21: axcp.v0_1.TelemetryDatagram
	(*DpParams)(nil),             // 22: axcp.v0_1.DpParams
	(*ErrorMessage)(nil),         // 23: axcp.v0_1.ErrorMessage
	(*McpJsonBlob)(nil),          // 24: axcp.v0_1.McpJsonBlob
	(*A2AJsonBlob)(nil),          // 25: axcp.v0_1.A2AJsonBlob
}
var file_axcp_proto_depIdxs = []int32{
	6,  // 0: axcp.v0_1.AxcpEnvelope.context_patch:type_name -> axcp.v0_1.ContextPatch
	14, // 1: axcp.v0_1.AxcpEnvelope.capability_msg:type_name -> axcp.v0_1.CapabilityMessage
	18, // 2: axcp.v0_1.AxcpEnvelope.route_msg:type_name -> axcp.v0_1.RoutePolicyMessage
	23, // 3: axcp.v0_1.AxcpEnvelope.error:type_name -> axcp.v0_1.ErrorMessage
	16, // 4: axcp.v0_1.AxcpEnvelope.profile_neg:type_name -> axcp.v0_1.ProfileNegotiate
	17, // 5: axcp.v0_1.AxcpEnvelope.profile_ack:type_name -> axcp.v0_1.ProfileAck
	10, // 6: axcp.v0_1.AxcpEnvelope.retry_env:type_name -> axcp.v0_1.RetryEnvelope
	21, // 7: axcp.v0_1.AxcpEnvelope.telemetry:type_name -> axcp.v0_1.TelemetryDatagram
	2,  // 8: axcp.v0_1.DeltaOp.op:type_name -> axcp.v0_1.DeltaOp.OpType
	5,  // 9: axcp.v0_1.ContextPatch.ops:type_name -> axcp.v0_1.DeltaOp
	7,  // 10: axcp.v0_1.SyncSubscribe.from:type_name -> axcp.v0_1.ContextGraphVersion
	7,  // 11: axcp.v0_1.SyncRequest.missing_from:type_name -> axcp.v0_1.ContextGraphVersion
	6,  // 12: axcp.v0_1.RetryEnvelope.buffered_patches:type_name -> axcp.v0_1.ContextPatch
	15, // 13: axcp.v0_1.CapabilityOffer.desc:type_name -> axcp.v0_1.CapabilityDescriptor
	11, // 14: axcp.v0_1.CapabilityMessage.offer:type_name -> axcp.v0_1.CapabilityOffer
	12, // 15: axcp.v0_1.CapabilityMessage.request:type_name -> axcp.v0_1.CapabilityRequest
	13, // 16: axcp.v0_1.CapabilityMessage.ack:type_name -> axcp.v0_1.CapabilityAck
	22, // 17: axcp.v0_1.CapabilityDescriptor.dp:type_name -> axcp.v0_1.DpParams
	19, // 18: axcp.v0_1.TelemetryDatagram.system:type_name -> axcp.v0_1.SystemStats
	20, // 19: axcp.v0_1.TelemetryDatagram.tokens:type_name -> axcp.v0_1.TokenUsage
	0,  // 20: axcp.v0_1.DpParams.mech:type_name -> axcp.v0_1.DpMechanism
	3,  // 21: axcp.v0_1.DpParams.gran:type_name -> axcp.v0_1.DpParams.Granularity
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_axcp_proto_init() }
func file_axcp_proto_init() {
	if File_axcp_proto != nil {
		return
	}
	file_axcp_proto_msgTypes[0].OneofWrappers = []any{
		(*AxcpEnvelope_ContextPatch)(nil),
		(*AxcpEnvelope_CapabilityMsg)(nil),
		(*AxcpEnvelope_RouteMsg)(nil),
		(*AxcpEnvelope_Error)(nil),
		(*AxcpEnvelope_ProfileNeg)(nil),
		(*AxcpEnvelope_ProfileAck)(nil),
		(*AxcpEnvelope_RetryEnv)(nil),
		(*AxcpEnvelope_Telemetry)(nil),
	}
	file_axcp_proto_msgTypes[10].OneofWrappers = []any{
		(*CapabilityMessage_Offer)(nil),
		(*CapabilityMessage_Request)(nil),
		(*CapabilityMessage_Ack)(nil),
	}
	file_axcp_proto_msgTypes[17].OneofWrappers = []any{
		(*TelemetryDatagram_System)(nil),
		(*TelemetryDatagram_Tokens)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_axcp_proto_rawDesc), len(file_axcp_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_axcp_proto_goTypes,
		DependencyIndexes: file_axcp_proto_depIdxs,
		EnumInfos:         file_axcp_proto_enumTypes,
		MessageInfos:      file_axcp_proto_msgTypes,
	}.Build()
	File_axcp_proto = out.File
	file_axcp_proto_goTypes = nil
	file_axcp_proto_depIdxs = nil
}
