name: Enterprise Secure Telemetry CI

on:
  push:
    branches:
      - 'enterprise/**'
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/enterprise-helm.yml'
  pull_request:
    branches:
      - 'enterprise/**'
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/enterprise-helm.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2
          args: --out-format=github-actions
          skip-cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Go vet + staticcheck
        run: |
          go vet -vettool=$(which staticcheck) ./...
      - name: Run tests with race detector & coverage
        run: |
          go test -race -coverprofile=coverage.out -covermode=atomic ./enterprise/...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
      # Dummy update to force GitHub Actions refresh