name: Enterprise Secure Telemetry CI

on:
  push:
    branches:
      - 'enterprise/**'
  pull_request:
    branches:
      - 'enterprise/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint & Vet
        run: |
          go vet -vettool=$(which staticcheck) ./...
          golangci-lint run --out-format colored-line-number

      - name: Run tests with race detector & coverage
        run: |
          go test -race -coverprofile=coverage.out -covermode=atomic ./enterprise/...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
