name: Rust Publish

on:
  push:
    tags:
      - 'axcp-rs-*'

jobs:
  publish:
    name: Publish Rust Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      
      - name: Install cargo-release
        run: |
          cargo install cargo-release --no-default-features

      - name: Configure Cargo registry
        run: |
          mkdir -p ~/.cargo
          echo '[registry]' > ~/.cargo/credentials.toml
          echo 'token = "${{ secrets.CARGO_REGISTRY_TOKEN }}"' >> ~/.cargo/credentials.toml
          chmod 600 ~/.cargo/credentials.toml

      - name: Publish to crates.io
        working-directory: sdk/rust
        run: |
          cargo publish --no-verify
